package app.logic._0_votesDownloader.model;

import java.io.Serializable;

public enum CategoryC1Enum implements Serializable{
	//AUTOVEICOLI_E_CICLI(""),
					AUTOMEZZI_COMMERCIALI(CategoryC0Enum.AUTOVEICOLI_E_CICLI, "593", "AUTOMEZZI COMMERCIALI"),
					MOTOVEICOLO_O_CICLOMOTORE(CategoryC0Enum.AUTOVEICOLI_E_CICLI, "594", "MOTOVEICOLO O CICLOMOTORE"),
					VEICOLI(CategoryC0Enum.AUTOVEICOLI_E_CICLI, "595", "VEICOLI"), 
					AUTOVETTURE(CategoryC0Enum.AUTOVEICOLI_E_CICLI, "596", "AUTOVETTURE"),
	
	//NAUTICA
					NAVI_E_GALLEGGIANTI(CategoryC0Enum.NAUTICA, "","NAVI E GALLEGGIANTI"),

	//MACCHINARI_UTENSILI_MATERIE_PRIME
					APPARECCHI_DI_SOLLEVAMENTO(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "","APPARECCHI DI SOLLEVAMENTO"),
	APPARECCHI_PER_L_INDUSTRIA_OTTICA(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
	FOTOCINEMATOGRAFICA_E_RADIOTELEVISIVA(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
					ATTREZZATURE_ED_UTENSILI(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "","ATTREZZATURE ED UTENSILI"),
					ATTREZZATURE_INDUSTRIALI(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "","ATTREZZATURE INDUSTRIALI"),
	ATTREZZATURE_MEDICHE(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
					ATTREZZATURE_VARIE(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "","ATTREZZATURE VARIE"),
	ELETTROMEDICALI(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
	MACCHINARI_PER_IL_CONFEZIONAMENTO_E_L_IMBALLAGGIO(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
					MACCHINARI_PER_L_AGRICOLTURA_FORESTE_E_PESCA(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "","MACCHINARI PER L'AGRICOLTURA, FORESTE E PESCA"),
	MACCHINARI_PER_L_ESTRAZIONE_DI_COMBUSTIBILI_E_MINERALI(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
					MACCHINARI_PER_L_INDUSTRIA_ALIMENTARE_E_CONSERVIERA(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "","MACCHINARI PER L'INDUSTRIA ALIMENTARE E CONSERVIERA"),
	MACCHINARI_PER_L_INDUSTRIA_CHIMICA_E_FARMACEUTICA(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
	MACCHINARI_PER_L_INDUSTRIA_POLIGRAFICA_EDITORIALE_ED_AFFINI(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
				MACCHINARI_PER_L_INDUSTRIA_TESSILE_LAVORAZIONE_PELLI_E_CALZATURE(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "","MACCHINARI PER L'INDUSTRIA TESSILE, LAVORAZIONE PELLI E CALZATURE"),
	MACCHINARI_PER_LA_LAVORAZIONE_DELLA_CERAMICA_DEI_LATERIZI_DEL_VETRO_E_DEL_MARMO(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
	MACCHINARI_PER_LA_LAVORAZIONE_DELLA_PLASTICA_E_GOMMA(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
	MACCHINARI_PER_LA_PRODUZIONE_ED_IL_TRATTAMENTO_DELLA_CARTA(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
	MACCHINARI_PER_LA_SALDATURA_TRATTAMENTI_TERMICI_SPECIALI_E_FONDERIA(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
	MACCHINARI_PER_LA_TERMOTECNICA(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
					MACCHINARI_IMPIANTI_ED_ATTREZZATURE_PER_L_EDILIZIA(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "","MACCHINARI, IMPIANTI ED ATTREZZATURE PER L'EDILIZIA"),
	MACCHINE_ED_ATTREZZATURE_PER_L_UFFICIO(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
	MACCHINE_OPERATRICI_REGISTRATE(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
	MACCHINE_OPERATRICI_TARGATE(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
					MACCHINE_PER_LA_LAVORAZIONE_DEI_METALLI(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "","MACCHINE PER LA LAVORAZIONE DEI METALLI"),
	MACCHINE_PER_LA_LAVORAZIONE_DEL_LEGNO_E_SIMILI(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "",""),
					MATERIE_PRIME_E_PRODOTTI(CategoryC0Enum.MACCHINARI_UTENSILI_MATERIE_PRIME, "","MATERIE PRIME E PRODOTTI"),

	//INFORMATICA_E_ELETTRONICA
					COMPUTER_E_ATTREZZATURA_INFORMATICA(CategoryC0Enum.INFORMATICA_E_ELETTRONICA, "","COMPUTER E ATTREZZATURA INFORMATICA"),

	
	//ARREDAMENTO_ED_ELETTRODOMESTICI
					ARREDI_DA_UFFICIO_E_VARIE(CategoryC0Enum.ARREDAMENTO_ED_ELETTRODOMESTICI, "","ARREDI DA UFFICIO E VARIE"),
					ELETTRODOMESTICI(CategoryC0Enum.ARREDAMENTO_ED_ELETTRODOMESTICI, "","ELETTRODOMESTICI"),
					MOBILI_DA_CASA_E_VARIE(CategoryC0Enum.ARREDAMENTO_ED_ELETTRODOMESTICI, "","MOBILI DA CASA E VARIE"),
					MOBILI_E_ARREDO_PER_UFFICIO(CategoryC0Enum.ARREDAMENTO_ED_ELETTRODOMESTICI, "","MOBILI E ARREDO PER UFFICIO"),

	
	//ARTE_OREFICERIA_OROLOGERIA_ANTIQUARIATO
					OGGETTI_D_ARTE_O_ANTIQUARIATO(CategoryC0Enum.ARTE_OREFICERIA_OROLOGERIA_ANTIQUARIATO, "","OGGETTI D'ARTE O ANTIQUARIATO"),
					PREZIOSI(CategoryC0Enum.ARTE_OREFICERIA_OROLOGERIA_ANTIQUARIATO, "","PREZIOSI"),

	
	//ABBIGLIAMENTO_E_CALZATURE
					ABBIGLIAMENTO_E_CALZATURE(CategoryC0Enum.ABBIGLIAMENTO_E_CALZATURE, "","ABBIGLIAMENTO E CALZATURE"),

	
	//ALTRA_CATEGORIA
	AEROMOBILE(CategoryC0Enum.ALTRA_CATEGORIA, "",""),
					BENE_GENERICO(CategoryC0Enum.ALTRA_CATEGORIA, "","BENE GENERICO"),
					COMMERCIO_AL_DETTAGLIO_RISTORAZIONE_E_INDUSTRIA_ALBERGHIERA(CategoryC0Enum.ALTRA_CATEGORIA, "","COMMERCIO AL DETTAGLIO, RISTORAZIONE E INDUSTRIA ALBERGHIERA"),
					MERCE_DEPERIBILE(CategoryC0Enum.ALTRA_CATEGORIA, "","MERCE DEPERIBILE"),
					MERCI_VARIE_NON_DEPERIBILI(CategoryC0Enum.ALTRA_CATEGORIA, "","MERCI VARIE NON DEPERIBILI");


	 
	


	  
    private final CategoryC0Enum macro;
	private final String code;
	private final String description;
	
	CategoryC1Enum(CategoryC0Enum macro, String code, String description) {
		 this.macro = macro;
		 this.code = code;
		 this.description = description;
	       
	    }

	    public String getCode() {
	        return code;
	    }

		public CategoryC0Enum getMacro() {
			return macro;
		}

	
		
		public static CategoryC1Enum findByDescription(String description){
		    for(CategoryC1Enum v : values()){
		        if( v.getDescription().equals(description)){
		            return v;
		        }
		    }
		    System.out.println(description);
		    return null;
		}

		public String getDescription() {
			return description;
		}
	    
}
