package app.logic._0_votesDownloader.model;

import java.io.Serializable;

public enum CategoryC1Enum implements Serializable{
	//AUTOVEICOLI_E_CICLI(""),
	AUTOMEZZI_COMMERCIALI(CategoryC0Enum.AUTOVEICOLI_E_CICLI, "593"),
	MOTOVEICOLO_O_CICLOMOTORE(CategoryC0Enum.AUTOVEICOLI_E_CICLI, "594"),
	VEICOLI(CategoryC0Enum.AUTOVEICOLI_E_CICLI, "595"), 
	AUTOVETTURE(CategoryC0Enum.AUTOVEICOLI_E_CICLI, "596");
//	
//	//NAUTICA
//	NAVI_E_GALLEGGIANTI,
//
//	//MACCHINARI_UTENSILI_MATERIE_PRIME
//	APPARECCHI_DI_SOLLEVAMENTO,
//	APPARECCHI_PER_L_INDUSTRIA_OTTICA,
//	FOTOCINEMATOGRAFICA_E_RADIOTELEVISIVA,
//	ATTREZZATURE_ED_UTENSILI,
//	ATTREZZATURE_INDUSTRIALI,
//	ATTREZZATURE_MEDICHE, 
//	ATTREZZATURE_VARIE,
//	ELETTROMEDICALI,
//	MACCHINARI_PER_IL_CONFEZIONAMENTO_E_L_IMBALLAGGIO
//	MACCHINARI_PER_L_AGRICOLTURA,_FORESTE_E_PESCA,
//	MACCHINARI_PER_L_ESTRAZIONE_DI_COMBUSTIBILI_E_MINERALI,
//	MACCHINARI_PER_L_INDUSTRIA_ALIMENTARE_E_CONSERVIERA,
//	MACCHINARI_PER_L_INDUSTRIA_CHIMICA_E_FARMACEUTICA,
//	MACCHINARI_PER_L_INDUSTRIA_POLIGRAFICA,_EDITORIALE_ED_AFFINI,
//	MACCHINARI_PER_L_INDUSTRIA_TESSILE,_LAVORAZIONE_PELLI_E_CALZATURE,
//	MACCHINARI_PER_LA_LAVORAZIONE_DELLA_CERAMICA,_DEI_LATERIZI,_DEL_VETRO_E_DEL_MARMO,
//	MACCHINARI_PER_LA_LAVORAZIONE_DELLA_PLASTICA_E_GOMMA,
//	MACCHINARI_PER_LA_PRODUZIONE_ED_IL_TRATTAMENTO_DELLA_CARTA,
//	MACCHINARI_PER_LA_SALDATURA,_TRATTAMENTI_TERMICI,_SPECIALI_E_FONDERIA,
//	MACCHINARI_PER_LA_TERMOTECNICA,
//	MACCHINARI,_IMPIANTI_ED_ATTREZZATURE_PER_L_EDILIZIA,
//	MACCHINE_ED_ATTREZZATURE_PER_L_UFFICIO,
//	MACCHINE_OPERATRICI_REGISTRATE,
//	MACCHINE_OPERATRICI_TARGATE,
//	MACCHINE_PER_LA_LAVORAZIONE_DEI_METALLI,
//	MACCHINE_PER_LA_LAVORAZIONE_DEL_LEGNO_E_SIMILI,
//	MATERIE_PRIME_E_PRODOTTI,
//
//	//INFORMATICA_E_ELETTRONICA
//	COMPUTER_E_ATTREZZATURA_INFORMATICA,
//
//	
//	//ARREDAMENTO_ED_ELETTRODOMESTICI
//	ARREDI_DA_UFFICIO_E_VARIE,
//	ELETTRODOMESTICI,
//	MOBILI_DA_CASA_E_VARIE,
//	MOBILI_E_ARREDO_PER_UFFICIO,
//
//	
//	//ARTE_OREFICERIA_OROLOGERIA_ANTIQUARIATO
//	OGGETTI_D_ARTE_O_ANTIQUARIATO,
//	PREZIOSI,
//
//	
//	//ABBIGLIAMENTO_E_CALZATURE
//	ABBIGLIAMENTO_E_CALZATURE,
//
//	
//	//ALTRA_CATEGORIA
//	AEROMOBILE,
//	BENE_GENERICO,
//	COMMERCIO_AL_DETTAGLIO,_RISTORAZIONE_E_INDUSTRIA_ALBERGHIERA,
//	MERCE_DEPERIBILE,
//	MERCI_VARIE_NON_DEPERIBILI,
//
//
	 
	


	  
    private final CategoryC0Enum macro;
	private final String code;
	
	CategoryC1Enum(CategoryC0Enum macro, String code) {
		 this.macro = macro;
		 this.code = code;
	       
	    }

	    public String getCode() {
	        return code;
	    }

		public CategoryC0Enum getMacro() {
			return macro;
		}
	    
}
