package app.logic._0_votesDownloader.model;

import java.io.Serializable;	

public enum ProceedingEnum implements Serializable{
	LIQUIDAZIONE_GIUDIZIALE_CCI("2217", "LIQUIDAZIONE GIUDIZIALE CCI"),
	ALTRO("893", "ALTRO"),
	CORPI_DI_REATO("411", "CORPI DI REATO"),
	ESECUZIONI_MOBILIARI_CON_VENDITA_POST_LEGGE_80("80411", "ESECUZIONI MOBILIARI CON VENDITA POST LEGGE 80"),
	FALLIMENTARE_NUOVO_RITO("309", "FALLIMENTARE nuovo rito"),
	FALLIMENTARE("271", "FALLIMENTARE"),
	EREDITÀ_GIACENTE("211", "EREDITÀ GIACENTE"),
	ESECUZIONI_MOBILIARI_CON_VENDITA("177", "ESECUZIONI MOBILIARI CON VENDITA"),
	LIQUIDAZIONE_VOLONTARIA_GIUDIZIALE("176", "LIQUIDAZIONE VOLONTARIA - GIUDIZIALE"),
	AMMINISTRAZIONE_GIUDIZIARIA("119", "AMMINISTRAZIONE GIUDIZIARIA"),
	ESATTORIALE("85", "ESATTORIALE"),
	CONFISCA("83", "CONFISCA"),
	ESECUZIONI_ESATTORIALI_MOBILIARI("76", "ESECUZIONI ESATTORIALI MOBILIARI"),
	RGE_MOBILIARE("71", "R.G.E. MOBILIARE"),
	LIQUIDAZIONE_CONTROLLATA_CCI("65", "LIQUIDAZIONE CONTROLLATA CCI"),
	ESPROPRIAZIONE_MOBILIARE_CARTABIA("57", "ESPROPRIAZIONE MOBILIARE CARTABIA"),
	NUOVO_CONCORDATO_PREVENTIVO("54", "NUOVO CONCORDATO PREVENTIVO"),
	RGE("53", "R.G.E."),
	LIQUIDAZIONE_COATTA_AMMINISTRATIVA("30", "LIQUIDAZIONE COATTA AMMINISTRATIVA"),
	VOLONTARIA_GIURISDIZIONE("23", "VOLONTARIA GIURISDIZIONE"),
	ESECUZIONE_IMMOBILIARI("18", "ESECUZIONE IMMOBILIARI"),
	ESECUZIONE_IMMOBILIARE_POST_LEGGE_80("8013", "ESECUZIONE IMMOBILIARE POST LEGGE 80"),
	DOGANALE("10", "DOGANALE"),
	LIQUIDAZIONE_DEL_PATRIMONIO("8", "LIQUIDAZIONE DEL PATRIMONIO"),
	PIANO_DEL_CONSUMATORE("6", "PIANO DEL CONSUMATORE"),
	CONCORDATO_PREVENTIVO("5", "CONCORDATO PREVENTIVO"),
	LIQUIDAZIONE_DEL_PATRIMONIO_DEL_DEBITORE("4", "LIQUIDAZIONE DEL PATRIMONIO DEL DEBITORE"),
	COSE_DEPOSITATE_ART_1789_CC("17893", "COSE DEPOSITATE Art. 1789 c.c."),
	ESECUZIONE_MOBILIARE_EX_ART_609("6093", "ESECUZIONE MOBILIARE EX ART. 609"),
	DEMANIO("2", "DEMANIO"),
	DIRITTO_DI_RITENZIONE("2", "DIRITTO DI RITENZIONE"),
	SEQUESTRO_GIUDIZIARIO("2", "SEQUESTRO GIUDIZIARIO"),
	CONCORDATO_SEMPLIFICATO_CCI("1", "CONCORDATO SEMPLIFICATO CCI"),
	ESPROPRIAZIONE_IMMOBILIARE_CARTABIA("1", "ESPROPRIAZIONE IMMOBILIARE CARTABIA");
	
	private final String code;
	private final String description;
	
	ProceedingEnum(String code, String description) {
	        this.code = code;
	        this.description= description;
	    }

	    public String getCode() {
	        return code;
	    }
	    
		public static ProceedingEnum findByDescription(String description){
		    for(ProceedingEnum v : values()){
		        if( v.getDescription().equals(description)){
		            return v;
		        }
		    }
//		    System.out.println(description);
		    return null;
		}

		public String getDescription() {
			return description;
		}
		
		
}
